# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chezmoui < Formula
  desc "A TUI for chezmoi."
  homepage "https://github.com/balintb/chezmoui"
  version "0.1.0"
  license "MIT"

  depends_on "chezmoi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balintb/chezmoui/releases/download/v0.1.0/chezmoui_0.1.0_darwin_x86_64.tar.gz"
      sha256 "b735920e22e2745f9d9cba869f7f485db3775c5b746851a5edaa1bd3467893c5"

      define_method(:install) do
        bin.install "cmui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balintb/chezmoui/releases/download/v0.1.0/chezmoui_0.1.0_darwin_arm64.tar.gz"
      sha256 "6c1f1acd25aca59c377b8706a86b755488b1ac94e1e1325cb4d43c20c9b1d6d8"

      define_method(:install) do
        bin.install "cmui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balintb/chezmoui/releases/download/v0.1.0/chezmoui_0.1.0_linux_x86_64.tar.gz"
      sha256 "0f55ab476625f8de1433d11d1ee48157369b9e986bd6622c5aa5c724bf5264b8"
      define_method(:install) do
        bin.install "cmui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balintb/chezmoui/releases/download/v0.1.0/chezmoui_0.1.0_linux_arm64.tar.gz"
      sha256 "57581bbb6118411ec4cc2e19c23d90eca68184e8f6288b713bf4ac8dee5028f0"
      define_method(:install) do
        bin.install "cmui"
      end
    end
  end

  test do
    system "#{bin}/cmui", "--version"
  end
end
