# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chezmoui < Formula
  desc "A TUI for chezmoi."
  homepage "https://github.com/balintb/chezmoui"
  version "0.2.0"
  license "MIT"

  depends_on "chezmoi"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/balintb/chezmoui/releases/download/v0.2.0/chezmoui_0.2.0_darwin_x86_64.tar.gz"
      sha256 "83c1505b912364ad4928afc550de7522d44f7b731ac3be494d57e92ffdcd2654"

      define_method(:install) do
        bin.install "cmui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/balintb/chezmoui/releases/download/v0.2.0/chezmoui_0.2.0_darwin_arm64.tar.gz"
      sha256 "89347d96b525fd4afd968e6962b6b4e5d96e3f2ec9db3f04ad810e625055343a"

      define_method(:install) do
        bin.install "cmui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/balintb/chezmoui/releases/download/v0.2.0/chezmoui_0.2.0_linux_x86_64.tar.gz"
      sha256 "346f4eb6f5ec131f938f9a1acb29acf0bf1dec9f4ea475dd031e320796eaf808"
      define_method(:install) do
        bin.install "cmui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/balintb/chezmoui/releases/download/v0.2.0/chezmoui_0.2.0_linux_arm64.tar.gz"
      sha256 "011e13b279ce38a79f59bc25fdb98f78040da8056d3f7ebdc73394848622cc97"
      define_method(:install) do
        bin.install "cmui"
      end
    end
  end

  test do
    system "#{bin}/cmui", "--version"
  end
end
