# Generated by scripts/bump-formula.sh on release. Prebuilt-binary formula:
# Homebrew downloads the release archive (no quarantine -> no notarization needed).
class ClaudeAfterlife < Formula
  desc "Reopen Claude Code sessions lost to a reboot or a terminal quitting"
  homepage "https://github.com/balintb/claude-afterlife"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.2.0/claude-afterlife_0.2.0_darwin_arm64.tar.gz"
      sha256 "6a3ce7cdd99a3b8e0dca5c6fc46f8fd023aa7bb6f5a018eb1d04e8ed20cd5132"
    end
    on_intel do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.2.0/claude-afterlife_0.2.0_darwin_amd64.tar.gz"
      sha256 "815fd6738e83193765f7d380f7d0e6ce8486e18861183327bb33f70c42c4beaa"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.2.0/claude-afterlife_0.2.0_linux_arm64.tar.gz"
      sha256 "78f0ea9b04852809026c808e9a9a52c7f854804408bc7812c8daebf332bfdabe"
    end
    on_intel do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.2.0/claude-afterlife_0.2.0_linux_amd64.tar.gz"
      sha256 "267a0e4856e865073fdd6b395fd09a8bbaafe45c3bf88ab7e0eace0182077d74"
    end
  end

  def install
    bin.install "claude-afterlife"
  end

  def caveats
    <<~EOS
      To record your running Claude Code sessions every minute, run:
        claude-afterlife install

      After a reboot or a terminal quit, reopen them with:
        claude-afterlife restore
    EOS
  end

  test do
    assert_match "claude-afterlife #{version}", shell_output("#{bin}/claude-afterlife version")
  end
end
