# Generated by scripts/bump-formula.sh on release. Prebuilt-binary formula:
# Homebrew downloads the release archive (no quarantine -> no notarization needed).
class ClaudeAfterlife < Formula
  desc "Reopen Claude Code sessions lost to a reboot or a terminal quitting"
  homepage "https://github.com/balintb/claude-afterlife"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.1.0/claude-afterlife_0.1.0_darwin_arm64.tar.gz"
      sha256 "b43a1a6d58ca07ad4197b94d06c196af4ef68428c6863da6b4f01e8b977edf7c"
    end
    on_intel do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.1.0/claude-afterlife_0.1.0_darwin_amd64.tar.gz"
      sha256 "b0f6b72849ba8a5b5ba6173da98df38893204905c8ef0a549ab9cd857795ab54"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.1.0/claude-afterlife_0.1.0_linux_arm64.tar.gz"
      sha256 "6e8d4dd789ada1e375bc8fd6ca41c1f85bded138a99aef0bca1adbebc16aee0e"
    end
    on_intel do
      url "https://github.com/balintb/claude-afterlife/releases/download/v0.1.0/claude-afterlife_0.1.0_linux_amd64.tar.gz"
      sha256 "fb4f91088218db2ac1aafafaf7f18a40904a3ddcc778e73b81e179ac08eb8298"
    end
  end

  def install
    bin.install "claude-afterlife"
  end

  def caveats
    <<~EOS
      To record your running Claude Code sessions every minute, run:
        claude-afterlife install

      After a reboot or a terminal quit, reopen them with:
        claude-afterlife restore
    EOS
  end

  test do
    assert_match "claude-afterlife #{version}", shell_output("#{bin}/claude-afterlife version")
  end
end
