# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipsyboogie < Formula
  desc "macOS cli clipboard logger
"
  homepage "https://github.com/balintb/clipsyboogie"
  version "0.1.1"
  license "MIT"

  depends_on "git"
  depends_on "npm"
  depends_on :macos

  on_intel do
    url "https://github.com/balintb/clipsyboogie/releases/download/v0.1.1/clipsyboogie_Darwin_x86_64.tar.gz"
    sha256 "8c11e5710976a081b00831372dd637b73577cd3eb141d537949cbf83debb46f8"

    def install
      bin.install "clipsyboogie"
    end
  end
  on_arm do
    url "https://github.com/balintb/clipsyboogie/releases/download/v0.1.1/clipsyboogie_Darwin_arm64.tar.gz"
    sha256 "ec41a7a9513b5121d9bb47af64f1ead1c4ad09d93a854b2e66ff95b48c25148c"

    def install
      bin.install "clipsyboogie"
    end
  end
end
