# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clipsyboogie < Formula
  desc "macOS cli clipboard logger
"
  homepage "https://github.com/balintb/clipsyboogie"
  version "0.1.0"
  license "MIT"

  depends_on "git"
  depends_on "npm"
  depends_on :macos

  on_intel do
    url "https://github.com/balintb/clipsyboogie/releases/download/v0.1.0/clipsyboogie_Darwin_x86_64.tar.gz"
    sha256 "b01fe566f97d947ff9cfffe648053331a5e93c735c29923a853702f5480418b4"

    def install
      bin.install "clipsyboogie"
    end
  end
  on_arm do
    url "https://github.com/balintb/clipsyboogie/releases/download/v0.1.0/clipsyboogie_Darwin_arm64.tar.gz"
    sha256 "bcc8bd1cad0716c7844f21d579de259b2ea63ebc3da393d7e058f58ff27e2fd2"

    def install
      bin.install "clipsyboogie"
    end
  end
end
