# Generated by scripts/bump-formula.sh on release. Prebuilt-binary formula:
# Homebrew downloads the release archive (no quarantine -> no notarization needed).
class Cz < Formula
  desc "Resume past Claude Code sessions without remembering their IDs"
  homepage "https://github.com/balintb/cz"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/balintb/cz/releases/download/v0.1.0/cz_0.1.0_darwin_arm64.tar.gz"
      sha256 "8821a2474abefeca7a5e15fd02d6211c55b32b80e37bf35d00ccf3d1743d8fcb"
    end
    on_intel do
      url "https://github.com/balintb/cz/releases/download/v0.1.0/cz_0.1.0_darwin_amd64.tar.gz"
      sha256 "8c9c0925220d489978f49019d7bf1141cc62a50fda7163c5f9184d8093cc7e5c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/balintb/cz/releases/download/v0.1.0/cz_0.1.0_linux_arm64.tar.gz"
      sha256 "6dbbceb536504a5ab2ce9b156da9a027ca64598ce769e5f5f93fe7fcb0715d98"
    end
    on_intel do
      url "https://github.com/balintb/cz/releases/download/v0.1.0/cz_0.1.0_linux_amd64.tar.gz"
      sha256 "57182c172fbbff8307d8d8bcdd72afe0e4f546b2d89bc205b484208850509845"
    end
  end

  def install
    bin.install "cz"
    generate_completions_from_executable(bin/"cz", "completion", shells: [:bash, :zsh, :fish])
  end

  test do
    assert_match "cz #{version}", shell_output("#{bin}/cz version")
  end
end
