# Generated by scripts/bump-formula.sh on release. Prebuilt-binary formula:
# Homebrew downloads the release archive (no quarantine -> no notarization needed).
class Llamago < Formula
  desc "TUI for Ollama: chat, manage installed models, compare them side by side"
  homepage "https://github.com/balintb/llamago"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/balintb/llamago/releases/download/v0.1.1/llamago_0.1.1_darwin_arm64.tar.gz"
      sha256 "87c10d730f07580e7f69a529c849e3884a9ba50597646d2a2477c91c68829cd0"
    end
    on_intel do
      url "https://github.com/balintb/llamago/releases/download/v0.1.1/llamago_0.1.1_darwin_amd64.tar.gz"
      sha256 "1d67561150d4c630484dfc0341224129869d2cb9370c1fd14d2f8ec41af6f936"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/balintb/llamago/releases/download/v0.1.1/llamago_0.1.1_linux_arm64.tar.gz"
      sha256 "cf1027de06b24e60d865fd4c14ffca9bca6e3a53c996914bb44c5366f5cef267"
    end
    on_intel do
      url "https://github.com/balintb/llamago/releases/download/v0.1.1/llamago_0.1.1_linux_amd64.tar.gz"
      sha256 "4b38d0730ab97f0530cb533416744004a164678b44c50b86e581b98c14ca340f"
    end
  end

  def install
    bin.install "llamago"
  end

  def caveats
    <<~EOS
      llamago talks to a running Ollama server and does not start one. For a local one:
        brew install ollama
        ollama serve

      Or point it at another server with: llamago -host http://host:11434
    EOS
  end

  test do
    assert_match "llamago v#{version}", shell_output("#{bin}/llamago -version")
  end
end
